### ISSUE TITLE
Update 2. To-Do

### ISSUE THREAD

**Issue by Sansaur** [Sansaur/VoreCode-BinxVersion#8]
- [ ] 1. Allow player to pick two options from ears and tails  **(No, we are just going to add combinations, doing this will bring problems)**
- [ ] 2. fix the electric chair
- [ ] 3. enzyme reclaimer **(What the fuck is this!?!?)**
- [ ] 4. Meat hooks to accept people
- [ ] 5. add feral code to all preds
- [ ] 6. fix broken shoving in lockers
- [ ] 7. fix bug of being able to resist and attack while unconcious
- [ ] 8.fix diffrent clothing looking wrong on cat people
- [ ] 9.Fix being able to have an animal or person in your belly nom you.
- [ ] 10.Fix being able to eat a beacon and then throw yourself into your own belly, and spacing yourself.
- [ ] 11. ........Defibs
- [ ] 12. Remains in stomach after digestion
- [ ] 13. micro squish eventually.......

**Comment by runeguden** [comment]
enzyme reclaimer, its hooked up to cloners and meat/corpses are put in, making synth meat, and adding it to the cloner, allowing an easy way to clone people

**Comment by kcin2001** [comment]
what exactly is no. 8's problem?

**Comment by Sansaur** [comment]
Masks don't look good on Tajarans

**Comment by kcin2001** [comment]
they dont look good on every snout
